CREATE TABLE IF NOT EXISTS customer (
    customer_id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    id_card VARCHAR(18) NOT NULL,
    age INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    monthly_income DECIMAL(12,2) NOT NULL DEFAULT 0,
    monthly_debt DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_rule (
    product_id VARCHAR(32) PRIMARY KEY,
    product_name VARCHAR(64) NOT NULL,
    min_age INT NOT NULL DEFAULT 18,
    max_age INT NOT NULL DEFAULT 60,
    min_income DECIMAL(12,2) NOT NULL DEFAULT 5000,
    max_debt_ratio DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    credit_factor DECIMAL(10,2) NOT NULL DEFAULT 12,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blacklist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id VARCHAR(32) NOT NULL,
    reason VARCHAR(128),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
