CREATE DATABASE IF NOT EXISTS waimai_alpha DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS waimai_beta  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
